// Aggregate all question data
// Note: Files are generated by subagents and must exist before this index is used
export { libraryScienceQuestions } from './library-science';
export { generalKnowledgeQuestions } from './general-knowledge';
export { biharGKQuestions } from './bihar-gk';
export { reasoningQuestions } from './reasoning';
export { computerQuestions } from './computer';

import { libraryScienceQuestions } from './library-science';
import { generalKnowledgeQuestions } from './general-knowledge';
import { biharGKQuestions } from './bihar-gk';
import { reasoningQuestions } from './reasoning';
import { computerQuestions } from './computer';
import type { Question, SubjectKey } from '@/types';

export const allQuestions: Question[] = [
  ...libraryScienceQuestions,
  ...generalKnowledgeQuestions,
  ...biharGKQuestions,
  ...reasoningQuestions,
  ...computerQuestions,
];

export function getQuestionsBySubject(subjectId: SubjectKey): Question[] {
  return allQuestions.filter(q => q.subject === subjectId);
}

export function getQuestionsByUnit(subjectId: SubjectKey, unitId: string): Question[] {
  return allQuestions.filter(q => q.subject === subjectId && q.unit === unitId);
}

export function getQuestionsByTopic(topicId: string): Question[] {
  return allQuestions.filter(q => q.topic === topicId);
}

export function getQuestionById(id: string): Question | undefined {
  return allQuestions.find(q => q.id === id);
}

export function getQuestionsByIds(ids: string[]): Question[] {
  const idSet = new Set(ids);
  return allQuestions.filter(q => idSet.has(q.id));
}
